# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        config: [Release, Debug]

    steps:
      - uses: actions/checkout@v2

      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1

      - run: MSBuild nvEncDXGI.sln /p:Configuration=${{ matrix.config }} /p:Platform=x64

      - uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.config }}
          path: x64\${{ matrix.config }}\Capture.exe
